// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyteQuery.Features.Database.Data;

#nullable disable

namespace SyteQuery.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260829133922_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.IdoDefinitionDb", b =>
                {
                    b.Property<string>("IdoName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevisionNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("XmlDefinition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdoName");

                    b.ToTable("IdoDefinitions");
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.QueryHistoryDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HistoryId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RowsAffected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExecutedAt");

                    b.HasIndex("UserId", "HistoryId")
                        .IsUnique();

                    b.ToTable("QueryHistory");
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.QuerySnippetDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SnippetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SnippetId")
                        .IsUnique();

                    b.ToTable("QuerySnippets");
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.ScheduledJobDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CronExpression")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmailConnectorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorEmailRecipients")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportFormat")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Excel");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultEmailRecipients")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RunOnceAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SendErrorsToEmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendResultsToEmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendResultsToWebhook")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WebhookConnectorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookHeaders")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "NextRunAt");

                    b.HasIndex("UserId", "JobId")
                        .IsUnique();

                    b.ToTable("ScheduledJobs");
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.ScheduledJobExecutionDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailError")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("EmailSent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduledJobId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TotalDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebhookError")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("WebhookSent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledJobId", "ExecutedAt");

                    b.ToTable("ScheduledJobExecutions");
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.ScheduledJobStepDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ContinueOnError")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduledJobId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StepId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StepName")
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledJobId", "StepOrder")
                        .IsUnique();

                    b.ToTable("ScheduledJobSteps");
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.ScheduledJobStepExecutionDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RowCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ScheduledJobExecutionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduledJobStepId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepName")
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledJobStepId");

                    b.HasIndex("ScheduledJobExecutionId", "StepOrder");

                    b.ToTable("ScheduledJobStepExecutions");
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.UserEnvironmentDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "EnvironmentId")
                        .IsUnique();

                    b.ToTable("UserEnvironments");
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.UserNotificationConnectorDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConnectorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPassword")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpUsername")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("UseSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookHeaders")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ConnectorId")
                        .IsUnique();

                    b.ToTable("UserNotificationConnectors");
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowAllDataByDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.QueryHistoryDb", b =>
                {
                    b.HasOne("SyteQuery.Features.Database.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.QuerySnippetDb", b =>
                {
                    b.HasOne("SyteQuery.Features.Database.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.ScheduledJobDb", b =>
                {
                    b.HasOne("SyteQuery.Features.Database.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.ScheduledJobExecutionDb", b =>
                {
                    b.HasOne("SyteQuery.Features.Database.Entities.ScheduledJobDb", "ScheduledJob")
                        .WithMany()
                        .HasForeignKey("ScheduledJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledJob");
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.ScheduledJobStepDb", b =>
                {
                    b.HasOne("SyteQuery.Features.Database.Entities.ScheduledJobDb", "ScheduledJob")
                        .WithMany("Steps")
                        .HasForeignKey("ScheduledJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledJob");
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.ScheduledJobStepExecutionDb", b =>
                {
                    b.HasOne("SyteQuery.Features.Database.Entities.ScheduledJobExecutionDb", "ScheduledJobExecution")
                        .WithMany("StepExecutions")
                        .HasForeignKey("ScheduledJobExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SyteQuery.Features.Database.Entities.ScheduledJobStepDb", "ScheduledJobStep")
                        .WithMany()
                        .HasForeignKey("ScheduledJobStepId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ScheduledJobExecution");

                    b.Navigation("ScheduledJobStep");
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.UserEnvironmentDb", b =>
                {
                    b.HasOne("SyteQuery.Features.Database.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.UserNotificationConnectorDb", b =>
                {
                    b.HasOne("SyteQuery.Features.Database.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.UserProfile", b =>
                {
                    b.HasOne("SyteQuery.Features.Database.Entities.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("SyteQuery.Features.Database.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.ScheduledJobDb", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("SyteQuery.Features.Database.Entities.ScheduledJobExecutionDb", b =>
                {
                    b.Navigation("StepExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
